
export const talents: TablentObject[] = [
  {
    name: 'Rafel Benitez',
    picture: "src/assets/img/avatar/pic1.png",
    profession: 'UIUX Designer',
    price: 50,
    rate: 4.5,
    favors: 23,
    endjobs: 41,
    skills: ['Prototyping', 'Prototyping', 'Prototyping', 'Prototyping', 'Prototyping'],
  },
  {
    name: 'Rafel Benitez',
    picture: "src/assets/img/avatar/pic2.png",
    profession: 'UIUX Designer',
    price: 50,
    rate: 4.5,
    favors: 23,
    endjobs: 41,
    skills: ['Prototyping', 'Prototyping', 'Prototyping', 'Prototyping', 'Prototyping'],
  },
  {
    name: 'Rafel Benitez',
    picture: "src/assets/img/avatar/pic3.png",
    profession: 'UIUX Designer',
    price: 50,
    rate: 4.5,
    favors: 23,
    endjobs: 41,
    skills: ['Prototyping', 'Prototyping', 'Prototyping', 'Prototyping', 'Prototyping'],
  },
  {
    name: 'Rafel Benitez',
    picture: "src/assets/img/avatar/pic4.png",
    profession: 'UIUX Designer',
    price: 50,
    rate: 4.5,
    favors: 23,
    endjobs: 41,
    skills: ['Prototyping', 'Prototyping', 'Prototyping', 'Prototyping', 'Prototyping'],
  },
  {
    name: 'Rafel Benitez',
    picture: "src/assets/img/avatar/pic1.png",
    profession: 'UIUX Designer',
    price: 50,
    rate: 4.5,
    favors: 23,
    endjobs: 41,
    skills: ['Prototyping', 'Prototyping', 'Prototyping', 'Prototyping', 'Prototyping'],
  },
  {
    name: 'Rafel Benitez',
    picture: "src/assets/img/avatar/pic2.png",
    profession: 'UIUX Designer',
    price: 50,
    rate: 4.5,
    favors: 23,
    endjobs: 41,
    skills: ['Prototyping', 'Prototyping', 'Prototyping', 'Prototyping', 'Prototyping'],
  },
  {
    name: 'Rafel Benitez',
    picture: "src/assets/img/avatar/pic3.png",
    profession: 'UIUX Designer',
    price: 50,
    rate: 4.5,
    favors: 23,
    endjobs: 41,
    skills: ['Prototyping', 'Prototyping', 'Prototyping', 'Prototyping', 'Prototyping'],
  },
];

export const categories = [
    "All", "Metaverse", "Web3", "Designers", "Developers", "Modelers", "AI Experts", "Animators", "Managers"
]